# Use an official Node.js runtime as the base image
FROM node:18.16-alpine as build
# Set the working directory in the container
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install Node.js dependencies
RUN npm install
# Copy the application code to the working directory
COPY . .
RUN npm run build-api

# Use an official Node.js runtime as the base image
FROM node:18.16-alpine
WORKDIR /app
RUN apk add --update netcat-openbsd
COPY --from=build /app/dist/api ./dist/api
COPY --from=build /app/node_modules ./node_modules

# Command to run the application
CMD ["sh", "-c", "while ! nc -z postgres-service 5432; do sleep 1; done; node dist/api/index.js"]
