# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /api/src

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Expose the port on which the application will run
EXPOSE 3000

# Command to run the application
CMD ["node", "index.ts"]
